spring:
  datasource:
    url: jdbc:mysql://47.99.54.20:3306/game-service?useSSL=false&useUnicode=true&characterEncoding=utf8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root123
