-- auto-generated definition
create table common_config
(
    id                 int auto_increment
        primary key,
    config_group       varchar(45)                        not null,
    config_key         varchar(45)                        not null,
    value              longtext charset utf8mb4           not null,
    state              tinyint  default 0                 not null,
    remark             mediumtext                         null,
    last_modified_time datetime default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP,
    constraint group_key
        unique (config_group, config_key)
)
    collate = utf8mb4_general_ci;

create index `group`
    on common_config (config_group);


INSERT INTO `game-service`.common_config (id, config_group, config_key, value, state, remark, last_modified_time) VALUES (2, 'top', '1', '{"category":"3D","channel":"GameMonetize","description":"Hello farmers! In the world of farm simulation games, its an amazing day for an incredible adventure simulation. Make use of your vacant land and turn it into a fertile, productive farm that everyone will want to visit! Gain farming experience and expand your borders to get more resources, create western style crops and raise cute animals for an amazing peaceful village life simulation! Its time to remove the chaff from the fields of the wild Wild West! Experience the serene charm of rural village life; A beautiful location with a view of the flowing river awaits you. Design your dream farm with lots of buildings and decorations.","gameUrl":"https://html5.gamemonetize.com/r459clg1msy6s04k8kfv1bdskk8gnql7/","height":"600","id":"49022","instructions":"Mouse and Click","tags":[".io Games"," 3D Games"," Arcade"," Baby Hazel"," Best Games"," Business"," Farm"," Simulation"],"thumbPicUrl":"https://img.gamemonetize.com/r459clg1msy6s04k8kfv1bdskk8gnql7/512x384.jpg","title":"Field of Dreams: Simulation Adventure","width":"800","internalCategory":3}', 1, null, '2023-12-19 05:59:35');
INSERT INTO `game-service`.common_config (id, config_group, config_key, value, state, remark, last_modified_time) VALUES (3, 'top', '2', '{"category":"Shooting","channel":"GameMonetize","description":"The magic soldiers fall from the sky, the bullets are like silver snakes, and the smoke of war is rolling in. This is a contest about the king of special forces. Hurry up and bring your guns to stand out in this competition. Remember that the dog will be the last victory!","gameUrl":"https://html5.gamemonetize.com/eitm2ciil0yavsyfoiydtas8db1ly065/","height":"480","id":"45512","instructions":"PC W A S D - Move click to shoot space - reload Phone Follow the game tutorial ","tags":[".io Games"," Gun"," Shoot"],"thumbPicUrl":"https://img.gamemonetize.com/eitm2ciil0yavsyfoiydtas8db1ly065/512x384.jpg","title":"Warrior Survival.io","width":"800","internalCategory":17}', 1, null, '2023-12-19 13:59:25');
INSERT INTO `game-service`.common_config (id, config_group, config_key, value, state, remark, last_modified_time) VALUES (4, 'top', '3', '{"category":"Action","channel":"GameMonetize","description":"Fight against those monsters residing in the abandoned dungeon. Upgrade your stats, Collect classes, Wizard, Archer and more that can help you in your battle, and save the world by defeating them all!","gameUrl":"https://html5.gamemonetize.com/cb4lyqk01r8nugfoqxnaps191l2xvq9f/","height":"720","id":"47878","instructions":"Left Mouse Button Touch Screen","tags":["2D"," Arena"," Battlegrounds"," Enemies"," Fantasy"," Fighting"," Magic"," Mobile"," RPG"],"thumbPicUrl":"https://img.gamemonetize.com/cb4lyqk01r8nugfoqxnaps191l2xvq9f/512x384.jpg","title":"Monsters Dungeon Battle","width":"1080","internalCategory":4}', 1, null, '2023-12-19 05:59:35');
INSERT INTO `game-service`.common_config (id, config_group, config_key, value, state, remark, last_modified_time) VALUES (5, 'top', '4', '{"category":"Shooting","channel":"GameMonetize","description":"High-octane 2D shooter. Jump into some quick and explosive shoot-em-up action! Play one of many fun game modes either solo or with a friend online! Each game mode has a different objective, such as Sniper where accuracy is rewarded, or Time Attack where maximum kills is the goal. Unlock hundreds of weapons and attachments, ranging from pistols, SMGs, assault rifles, LMGs, sniper rifles, and more! Enter the firing range where all weapons and attachments are immediately accessible.","gameUrl":"https://html5.gamemonetize.com/fadsdximj0ao2vsyuswwntlarkxe1ns5/","height":"720","id":"50872","instructions":"Desktop Mouse keyboard Mobile Tap","tags":["2D"," Arcade"," Casual"," Gun"," Mobile"," Multiplayer"," Shoot \'Em Up"," Shooter"," Shooting"," Simulation"],"thumbPicUrl":"https://img.gamemonetize.com/fadsdximj0ao2vsyuswwntlarkxe1ns5/512x384.jpg","title":"Arsenal Online","width":"1280","internalCategory":17}', 1, null, '2023-12-19 05:59:35');
INSERT INTO `game-service`.common_config (id, config_group, config_key, value, state, remark, last_modified_time) VALUES (6, 'game_provider', 'gamemonetize', '{"providerUrl":"https://gamemonetize.com/feed.php"}', 1, null, '2023-12-15 09:53:13');
INSERT INTO `game-service`.common_config (id, config_group, config_key, value, state, remark, last_modified_time) VALUES (7, 'top', '5', '{"category":"Puzzle","channel":"GameMonetize","description":"Three amazing and fastest automobiles are in these eight photographs. You are able to select a single in the beginning. Subsequent step will be to find one thing which can be hidden in that image. That is certainly 15 car tires. Use mouse and click on the tire after you see one particular. The time is limited so be quickly and discover all hidden tires prior to time runs out. For those who do extra blunders the game will likely be more than. So, for anyone who is ready start out the game and have fun!","gameUrl":"https://html5.gamemonetize.com/q0tp0bykd4lmzj104i7yobr69i5he9kv/","height":"720","id":"51139","instructions":"Use mouse or touch on the screen ","tags":["Best"," Best Games"," Car"," Cars"," Casual"," Fun"," Funny"," Hidden"," Kids"," Mobile"," Skill"],"thumbPicUrl":"https://img.gamemonetize.com/q0tp0bykd4lmzj104i7yobr69i5he9kv/512x384.jpg","title":"Hidden Car Tires","width":"1280","internalCategory":15}', 1, null, '2023-12-19 05:59:35');
INSERT INTO `game-service`.common_config (id, config_group, config_key, value, state, remark, last_modified_time) VALUES (8, 'top', '6', '{"category":"Action","channel":"GameMonetize","description":"Are you ready for a competitive duel? Fight against the computer with your friend or alone! Start the fun with multiple game modes and maps!","gameUrl":"https://html5.gamemonetize.com/fh2qwe2glfh2n9pqdo995mi1p8fe66ch/","height":"720","id":"51027","instructions":"Player 1 W A D Movement S Block R Change Weapon Space Attack Player 2 Arrow Keys Movement Down Arrow Block O Change Weapon P Attack","tags":["1 Player"," 2 Player"," 2D"," Action"," Battle"," Block"," Pixel"," Platform"],"thumbPicUrl":"https://img.gamemonetize.com/fh2qwe2glfh2n9pqdo995mi1p8fe66ch/512x384.jpg","title":"Duel Time","width":"1280","internalCategory":4}', 1, null, '2023-12-19 05:59:35');
INSERT INTO `game-service`.common_config (id, config_group, config_key, value, state, remark, last_modified_time) VALUES (9, 'top', '7', '{"category":"Adventure","channel":"GameMonetize","description":"Introducing the adrenaline-pumping Anti-Virus Game! Arm yourself with epic tools, dive into the virtual world, and take down diabolical viruses. Embark on a mission to safeguard your digital domain, showcasing your tactical prowess and lightning-fast reflexes. Unleash your inner hero and ensure your devices stay virus-free in this thrilling gaming experience.","gameUrl":"https://html5.gamemonetize.com/hrm17c127o6nlljqcmc8lokhtpyh07xc/","height":"600","id":"50891","instructions":"Mouse click or tap to play","tags":["Action"," Adventure"," Air"," airplane"," Best Games"," Clicker"," free games for your site"," free html5 games for your website"," HTML"," Kids"," War"],"thumbPicUrl":"https://img.gamemonetize.com/hrm17c127o6nlljqcmc8lokhtpyh07xc/512x384.jpg","title":"AntiVirus / War Virus","width":"800","internalCategory":5}', 1, null, '2023-12-19 05:59:35');
INSERT INTO `game-service`.common_config (id, config_group, config_key, value, state, remark, last_modified_time) VALUES (10, 'top', '8', '{"category":"Stickman","channel":"GameMonetize","description":"An exciting strategic merge game where you have to demonstrate your advantage over the red stickman invaders. Create your army of stickmen, show your wit in the formation of troops and defeat all bosses. Less than 1% percent of players are able to unlock all stickmen and complete the game. - 3D stickmen - Each level is harder than the previous one - Intuitive controls - Boss difficulty every ten levels - Tactical game for all ages","gameUrl":"https://html5.gamemonetize.com/obyhafhugknxn37yy4vsed6yknb9d6rl/","height":"1080","id":"50907","instructions":"- Click Sword and arrow button to purchase units - Click Tile button to purchase tiles - Drag units between tiles to improve your strategic positioning - Merge two units of the same type to get the next tier unit","tags":["1 Player"," 3D"," Action"," Arena"," Army"," Battle"," Bow"," Clash"," Enemy"," Fight"," Hypercasual"," Management"," Stickman"," Strategy"],"thumbPicUrl":"https://img.gamemonetize.com/obyhafhugknxn37yy4vsed6yknb9d6rl/512x384.jpg","title":"Stickman Merge Battle: Arena","width":"1920","internalCategory":20}', 1, null, '2023-12-19 05:59:35');
INSERT INTO `game-service`.common_config (id, config_group, config_key, value, state, remark, last_modified_time) VALUES (11, 'game_feed_mode', 'SOLE', 'GameMonetize', 1, null, '2023-12-15 09:27:06');
INSERT INTO `game-service`.common_config (id, config_group, config_key, value, state, remark, last_modified_time) VALUES (12, 'game_feed_mode', 'MIX', '[{"channel":"GameMonetize","weight":100}]', 0, null, '2023-12-15 09:37:35');
